### ISSUE TITLE
Please add future Crystals to help with planning

### ISSUE THREAD

**Issue by enshoe** [Ihellmasker/BDO-Planner#19]
Hi, please add the WON, BON & JIN variants of the crystals to aid with future planning.
They were introduced with Kamasylve in KR and will most probably carried over.

They are on bddatabase, just search for WON, BON & JIN.

Thanks!

**Comment by Shadowtrance** [comment]
Yep I'm aware of the new crystals and they will be added when we get them like everything else, i don't add it until NA/EU actually has it... mainly so i don't have to go back and edit stuff a 2nd time because of translation differences. :)
But we should have kamasylve soon anyway i think. (hopefully).
I may add them early though. maybe. :P

**Comment by enshoe** [comment]
It's a fair point.

If you feel like you have the time I would appriciate it greatly. Makes planning a lot easier.
Maby add a comment about them not being ingame yet? Even though that would probably net you even more work ;)

**Comment by Shadowtrance** [comment]
I thought there was more than that for some reason. haha Only 6 of each total, 18 all up.
Might add them tomorrow, because why the hell not! :D

**Comment by Shadowtrance** [comment]
And they are now added and live. :)
Enjoy!
