### ISSUE TITLE
Accuracy/Evasion on Crystals/Alch Stones

### ISSUE THREAD

**Issue by xCrypticuzX** [Ihellmasker/BDO-Planner#27]
So you might want to change the wording on a few things. All Accuracy =/= Accuracy. All Evasion =/= Evasion. Armor, Weapons and Accessories give Accuracy and Evasion. Crystals, Alch Stones, Food and Elixirs give All Accuracy and All Evasion. Accuracy = All Accuracy / 4. Evasion = All Evasion / 4.

**Comment by AlecHolt** [comment]
Cryptic, can you prove this? or do you have any sources that can derive this?

**Comment by xCrypticuzX** [comment]
well for one, if you don't already know the correlation then i have no idea why you're even commenting on this. anyone and everyone knows that the changes in the patch in question were just description changes. Remember that all gems, buffs etc that were changed stated "Accuracy" now they're "All Accuracy" and are *4 larger. Same goes for evasion, and all evasion in the same regard. Putting it more simply, if all accuracy = accuracy, then precision gems should give more flat accuracy than TRI RCE which is simply not the case. Nothing was buffed. Nothing was nerfed.

**Comment by AlecHolt** [comment]
your claim was that Accuracy = All accuracy / 4 & Evasion = All Evasion / 4. the patch notes indeed do say that it was just a text change but this has very little to do with your claim. or maybe it doesn't to you, because you seem to be making connections based off of correlation yet ignoring other pieces of evidence that don't suit your claim and that correlation. For example: Accuracy enhancer went from Accuracy + 3 -> All Accuracy +6. or imperfect alchemy stone of destruction going from Accuracy + 1 -> All Accuracy +2. now we can understand these changes as just saying that they originally didn't have the correct accuracy/evasion rating, and now they're fixed. but with the amount of problems in the game it is still possible that some items have the word "Accuracy" when they should be "All Accuracy" or vice versa. its also possible that this change was meant to equalize both "Accuracy" and "All Accuracy". What I was originally asking for was not a simple outburst where you were offended by my original question, but an explanation of how you reached your conclusion or even better: literal statistics to back up the claim. I for one also believe that All Accuracy and Accuracy are different by a factor of 4 due to the fact of RCE being extremely effective. However providing a basis for your claim and allowing others to ask questions and debate it are basic fundamentals of proving something. saying things like "I have no idea why you're even commenting on this" or "anyone and everyone knows" are a weak argument in any case, especially when correlation =/= proof.

**Comment by xCrypticuzX** [comment]
sorry don't check back here often. But yea, for statistical evidence you already spoke of what i would've referenced. Red coral earrings (even tree spirit belt). Was going to say, if you think that they changed anything more than the description, then do you truly believe that gems now give more flat accuracy than TET red coral earrings? That'd just be silly.
