### ISSUE TITLE
Suggestion: Unlock Mystic?

### ISSUE THREAD

**Issue by bbygurl** [Ihellmasker/BDO-Planner#46]
Hi I was just curious, if you could unlock the mystic panel? Since she uses the same exact main and offhand as Striker. Or is there some information missing that you need before unlocking her?

**Comment by Shadowtrance** [comment]
Only missing stuff for mystic is her awakening weapon (i have the stats data as it's the same as all others, just no name to go with it).
Besides that, as you've probably noticed (or not) i prefer to unlock/add new stuff when we get it in NA/EU rather than beforehand so i don't have to go back and change stats or names or whatever when i could just wait and not need to. :)

**Comment by bbygurl** [comment]
Apparently the name is Blue Wave Kick, but yeah i understand. Thanks for the response :smile:

**Comment by Shadowtrance** [comment]
Well we now have a release date :) December 13, pre-creation December 6. I may unlock her on the 6th, obviously with no awakening weapon unless we have the "kakao item name translation" by then, if we do I'll add that too. :)

**Comment by bbygurl** [comment]
Yay sweet \o/ , thankss

**Comment by Shadowtrance** [comment]
She will be unlocked next week during maintenance. :)
