### ISSUE TITLE
stats on shield

### ISSUE THREAD

**Issue by THELYNXY** [Ihellmasker/BDO-Planner#55]
Ulimate krea shield missing +3 monster ap 
evasion 26 +52 not 23 +46
damage reduction 4 not 7

Ulimate Vangertz shield missing +3 monster ap
0 hidden evasion not 46

Ulimate Rosar Shield missing +3 monster ap 
evasion 26 +52 not 23 +46
damage reduction 4 not 7

**Comment by THELYNXY** [comment]
all on tri

**Comment by Shadowtrance** [comment]
Yes I'm aware of the stat issues with rosar offhands and possibly some krea offhands (seems it isn't just shields upon further investigation, was reported in our discord).

**ALL** main weps and offhands are missing the extra monster damage that was added err last week? was it i think.

As for vangertz evasion, well that's a special case as hidden evasion is either melee, magic or ranged and is all 3 on everything except vangertz, saiyer and leather offhands. Saiyer is only ranged, vangertz and leather are ranged and magic which is why you probably see 0 hidden evasion (looking at it on valk or warrior), look at it on a witch or ranger and you'll see the 23 (46).
Same with saiyer and leather pretty much. It is quite annoying how they've done that...Soooooo I've just put it all under the "Hidden Evasion" (for now at least) regardless of class.

Hope that helps explain that a little. :)
Not sure when I'll get around to fixing it all, to be quite honest i need a break after the massive hidden stats up. haha
Until then, just pretend they're still hidden. haha :)

**Comment by THELYNXY** [comment]
ty for the fast respons, en keep up the good work i love the work what you guys do

**Comment by Shadowtrance** [comment]
Ok back from my break...

Fixed (hopefully) all those Rosar / Krea offhand stats that were wrong.
If you spot  any more issues with them, please to let me know. :)

Now the fun part...adding the monster dmg to every freakin weapon...that's gonna take a bit.

**Comment by Shadowtrance** [comment]
This SHOULD be all fixed and monster damage has been added. :)
