### ISSUE TITLE
Suggestion: Real Gear Score

### ISSUE THREAD

**Issue by Sandaemon** [Ihellmasker/BDO-Planner#59]
The original "visible" stats are only half the gear and with the hidden stats being revealed I am interested in my real gear score; a total of ALL DR, Evasion and AP. Additionally, Accuracy was something else that was completely ignored on gear score.

Now we have all this info for real It would be nice to see the "real" gear score. I currently have a spreadsheet I keep all this on but would be much better on here as an additional stat.

Real gear score = all AP + all DR + all Evasion + all Accuracy  (And include gems too, they are gear after all)

**Comment by Ihellmasker** [comment]
Bit of a late response to this sorry, but, it's hard to consider anything a "real gear score" when the game doesn't have anything set down for what is a gear score. It's just one persons opinion against another really.

We went with AP + DP because at the time that was the community consensus on what was considered a gear score.
