### ISSUE TITLE
Missing file in the sources?

### ISSUE THREAD

**Issue by RiskyBomberPT** [Ihellmasker/BDO-Planner#6]
I tried to run this on localhost to mess around with it locally, mostly for self-education and learning from this application's source code, however it seems that there's a missing file in the /php/ folder called ga.php?

The application is running fine apparently, haven't faced problems so far, however I'm getting a PHP Warning about that missing file, so I thought I'd let you know.

"Warning: include(C:/xampp/htdocs/php/ga.php): failed to open stream: No such file or directory in C:\xampp\htdocs\index.php on line 487"

**Comment by Ihellmasker** [comment]
Yeah, some files are removed because they provide information from our server as per the note at the bottom of front page. That file can be safely ignored, just remove that line.

I will be putting template files up at some point for the missing files but right now it's not particularly a priority.

You will also have issues with short links as the files they require are also missing.

**Comment by RiskyBomberPT** [comment]
Thanks for the quick response!

My bad, I didn't notice the note
I'll just remove the said line and keep on going, thanks!
