### ISSUE TITLE
Cristals

### ISSUE THREAD

**Issue by hemisfere** [Ihellmasker/BDO-Planner#9]
- add all cristals

**Comment by Ihellmasker** [comment]
What is missing?

**Comment by Shadowtrance** [comment]
Crystals

This is not helpful at all...
Maybe post a short sentence of what the actual issue is, we aren't mind readers.
This is basically like someone commenting and saying "hey, it doesn't work!"... **WHAT** doesn't work, or in this case, **WHAT** is the issue.
Yes, I'm going to keep repeating myself...

**Comment by hemisfere** [comment]
CRYSTAL SOCKETS
Helmet:
- Dim Magical Crystal: Combat
- Dim Magical Crystal: Karma
:))

**Comment by Shadowtrance** [comment]
Dim Magical Crystals added.
